# Generated by Django 4.2.7 on 2023-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVis', '0002_alter_energy_options_rename_type_energy_energytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='energyUsed',
            field=models.FloatField(),
        ),
    ]
